// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg48TARcLnQauoPH86xID1htJzFwnoOSA',
    appId: '1:744839813017:web:156901ed30abc47ba72508',
    messagingSenderId: '744839813017',
    projectId: 'storefront-20f13',
    authDomain: 'storefront-20f13.firebaseapp.com',
    storageBucket: 'storefront-20f13.firebasestorage.app',
    measurementId: 'G-5K6HQXVQ6E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeQb7-kq0atmf0PjxXC0UqpbIguZFEKNY',
    appId: '1:744839813017:android:c0091c1cb1fcb887a72508',
    messagingSenderId: '744839813017',
    projectId: 'storefront-20f13',
    storageBucket: 'storefront-20f13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgApkXQCAt-OVCapTUikXzxOza7zMHp8U',
    appId: '1:744839813017:ios:1e4e0bcc26bd448fa72508',
    messagingSenderId: '744839813017',
    projectId: 'storefront-20f13',
    storageBucket: 'storefront-20f13.firebasestorage.app',
    iosClientId: '744839813017-dfl88fjtprg1dgpvlbb72fq37i5esb5j.apps.googleusercontent.com',
    iosBundleId: 'com.example.storefront',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgApkXQCAt-OVCapTUikXzxOza7zMHp8U',
    appId: '1:744839813017:ios:1e4e0bcc26bd448fa72508',
    messagingSenderId: '744839813017',
    projectId: 'storefront-20f13',
    storageBucket: 'storefront-20f13.firebasestorage.app',
    iosClientId: '744839813017-dfl88fjtprg1dgpvlbb72fq37i5esb5j.apps.googleusercontent.com',
    iosBundleId: 'com.example.storefront',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCg48TARcLnQauoPH86xID1htJzFwnoOSA',
    appId: '1:744839813017:web:712077364075bd63a72508',
    messagingSenderId: '744839813017',
    projectId: 'storefront-20f13',
    authDomain: 'storefront-20f13.firebaseapp.com',
    storageBucket: 'storefront-20f13.firebasestorage.app',
    measurementId: 'G-DP7H9NLEKW',
  );

}